=== trowgundam/pokemon_field_guide/schemas/package-manifest-v3.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://pokemon-field-guide.local/schemas/package-manifest-v3.schema.json",
  "type": "object",
  "properties": {
    "formatVersion": {
      "type": "integer",
      "minimum": 3,
      "maximum": 3,
      "const": 3
    },
    "pokemonSprites": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "pokemonSpritesByVersion": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      }
    },
    "areaAliases": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "areaMapsByVersion": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": {
          "type": "object",
          "properties": {
            "image": {
              "type": "string",
              "minLength": 1
            },
            "width": {
              "type": "integer",
              "minimum": 1,
              "maximum": 2147483647
            },
            "height": {
              "type": "integer",
              "minimum": 1,
              "maximum": 2147483647
            }
          },
          "required": [
            "image",
            "width",
            "height"
          ],
          "additionalProperties": false
        }
      }
    }
  },
  "required": [
    "formatVersion",
    "pokemonSprites",
    "areaAliases",
    "areaMapsByVersion"
  ],
  "additionalProperties": false
}

=== trowgundam/pokemon_field_guide/PokemonFieldGuide/wwwroot/games/crystal/data/package-manifest.json
{"formatVersion":3,"pokemonSprites":{"SPECIES_BULBASAUR":"bulbasaur.png","SPECIES_IVYSAUR":"ivysaur.png","SPECIES_VENUSAUR":"venusaur.png","SPECIES_CHARMANDER":"charmander.png","SPECIES_CHARMELEON":"charmeleon.png","SPECIES_CHARIZARD":"charizard.png","SPECIES_SQUIRTLE":"squirtle.png","SPECIES_WARTORTLE":"wartortle.png","SPECIES_BLASTOISE":"blastoise.png","SPECIES_CATERPIE":"caterpie.png","SPECIES_METAPOD":"metapod.png","SPECIES_BUTTERFREE":"butterfree.png","SPECIES_WEEDLE":"weedle.png","SPECIES_KAKUNA":"kakuna.png","SPECIES_BEEDRILL":"beedrill.png","SPECIES_PIDGEY":"pidgey.png","SPECIES_PIDGEOTTO":"pidgeotto.png","SPECIES_PIDGEOT":"pidgeot.png","SPECIES_RATTATA":"rattata.png","SPECIES_RATICATE":"raticate.png","SPECIES_SPEAROW":"spearow.png","SPECIES_FEAROW":"fearow.png","SPECIES_EKANS":"ekans.png","SPECIES_ARBOK":"arbok.png","SPECIES_PIKACHU":"pikachu.png","SPECIES_RAICHU":"raichu.png","SPECIES_SANDSHREW":"sandshrew.png","SPECIES_SANDSLASH":"sandslash.png","SPECIES_NIDORAN_F":"nidoran_f.png","SPECIES_NIDORINA":"nidorina.png","SPECIES_NIDOQUEEN":"nidoqueen.png","SPECIES_NIDORAN_M":"nidoran_m.png","SPECIES_NIDORINO":"nidorino.png","SPECIES_NIDOKING":"nidoking.png","SPECIES_CLEFAIRY":"clefairy.png","SPECIES_CLEFABLE":"clefable.png","SPECIES_VULPIX":"vulpix.png","SPECIES_NINETALES":"ninetales.png","SPECIES_JIGGLYPUFF":"jigglypuff.png","SPECIES_WIGGLYTUFF":"wigglytuff.png","SPECIES_ZUBAT":"zubat.png","SPECIES_GOLBAT":"golbat.png","SPECIES_ODDISH":"oddish.png","SPECIES_GLOOM":"gloom.png","SPECIES_VILEPLUME":"vileplume.png","SPECIES_PARAS":"paras.png","SPECIES_PARASECT":"parasect.png","SPECIES_VENONAT":"venonat.png","SPECIES_VENOMOTH":"venomoth.png","SPECIES_DIGLETT":"diglett.png","SPECIES_DUGTRIO":"dugtrio.png","SPECIES_MEOWTH":"meowth.png","SPECIES_PERSIAN":"persian.png","SPECIES_PSYDUCK":"psyduck.png","SPECIES_GOLDUCK":"golduck.png","SPECIES_MANKEY":"mankey.png","SPECIES_PRIMEAPE":"primeape.png","SPECIES_GROWLITHE":"growlithe.png","SPECIES_ARCANINE":"arcanine.png","SPECIES_POLIWAG":"poliwag.png","SPECIES_POLIWHIRL":"poliwhirl.png","SPECIES_POLIWRATH":"poliwrath.png","SPECIES_ABRA":"abra.png","SPECIES_KADABRA":"kadabra.png","SPECIES_ALAKAZAM":"alakazam.png","SPECIES_MACHOP":"machop.png","SPECIES_MACHOKE":"machoke.png","SPECIES_MACHAMP":"machamp.png","SPECIES_BELLSPROUT":"bellsprout.png","SPECIES_WEEPINBELL":"weepinbell.png","SPECIES_VICTREEBEL":"victreebel.png","SPECIES_TENTACOOL":"tentacool.png","SPECIES_TENTACRUEL":"tentacruel.png","SPECIES_GEODUDE":"geodude.png","SPECIES_GRAVELER":"graveler.png","SPECIES_GOLEM":"golem.png","SPECIES_PONYTA":"ponyta.png","SPECIES_RAPIDASH":"rapidash.png","SPECIES_SLOWPOKE":"slowpoke.png","SPECIES_SLOWBRO":"slowbro.png","SPECIES_MAGNEMITE":"magnemite.png","SPECIES_MAGNETON":"magneton.png","SPECIES_FARFETCH_D":"farfetch_d.png","SPECIES_DODUO":"doduo.png","SPECIES_DODRIO":"dodrio.png","SPECIES_SEEL":"seel.png","SPECIES_DEWGONG":"dewgong.png","SPECIES_GRIMER":"grimer.png","SPECIES_MUK":"muk.png","SPECIES_SHELLDER":"shellder.png","SPECIES_CLOYSTER":"cloyster.png","SPECIES_GASTLY":"gastly.png","SPECIES_HAUNTER":"haunter.png","SPECIES_GENGAR":"gengar.png","SPECIES_ONIX":"onix.png","SPECIES_DROWZEE":"drowzee.png","SPECIES_HYPNO":"hypno.png","SPECIES_KRABBY":"krabby.png","SPECIES_KINGLER":"kingler.png","SPECIES_VOLTORB":"voltorb.png","SPECIES_ELECTRODE":"electrode.png","SPECIES_EXEGGCUTE":"exeggcute.png","SPECIES_EXEGGUTOR":"exeggutor.png","SPECIES_CUBONE":"cubone.png","SPECIES_MAROWAK":"marowak.png","SPECIES_HITMONLEE":"hitmonlee.png","SPECIES_HITMONCHAN":"hitmonchan.png","SPECIES_LICKITUNG":"lickitung.png","SPECIES_KOFFING":"koffing.png","SPECIES_WEEZING":"weezing.png","SPECIES_RHYHORN":"rhyhorn.png","SPECIES_RHYDON":"rhydon.png","SPECIES_CHANSEY":"chansey.png","SPECIES_TANGELA":"tangela.png","SPECIES_KANGASKHAN":"kangaskhan.png","SPECIES_HORSEA":"horsea.png","SPECIES_SEADRA":"seadra.png","SPECIES_GOLDEEN":"goldeen.png","SPECIES_SEAKING":"seaking.png","SPECIES_STARYU":"staryu.png","SPECIES_STARMIE":"starmie.png","SPECIES_MR__MIME":"mr__mime.png","SPECIES_SCYTHER":"scyther.png","SPECIES_JYNX":"jynx.png","SPECIES_ELECTABUZZ":"electabuzz.png","SPECIES_MAGMAR":"magmar.png","SPECIES_PINSIR":"pinsir.png","SPECIES_TAUROS":"tauros.png","SPECIES_MAGIKARP":"magikarp.png","SPECIES_GYARADOS":"gyarados.png","SPECIES_LAPRAS":"lapras.png","SPECIES_DITTO":"ditto.png","SPECIES_EEVEE":"eevee.png","SPECIES_VAPOREON":"vaporeon.png","SPECIES_JOLTEON":"jolteon.png","SPECIES_FLAREON":"flareon.png","SPECIES_PORYGON":"porygon.png","SPECIES_OMANYTE":"omanyte.png","SPECIES_OMASTAR":"omastar.png","SPECIES_KABUTO":"kabuto.png","SPECIES_KABUTOPS":"kabutops.png","SPECIES_AERODACTYL":"aerodactyl.png","SPECIES_SNORLAX":"snorlax.png","SPECIES_ARTICUNO":"articuno.png","SPECIES_ZAPDOS":"zapdos.png","SPECIES_MOLTRES":"moltres.png","SPECIES_DRATINI":"dratini.png","SPECIES_DRAGONAIR":"dragonair.png","SPECIES_DRAGONITE":"dragonite.png","SPECIES_MEWTWO":"mewtwo.png","SPECIES_MEW":"mew.png","SPECIES_CHIKORITA":"chikorita.png","SPECIES_BAYLEEF":"bayleef.png","SPECIES_MEGANIUM":"meganium.png","SPECIES_CYNDAQUIL":"cyndaquil.png","SPECIES_QUILAVA":"quilava.png","SPECIES_TYPHLOSION":"typhlosion.png","SPECIES_TOTODILE":"totodile.png","SPECIES_CROCONAW":"croconaw.png","SPECIES_FERALIGATR":"feraligatr.png","SPECIES_SENTRET":"sentret.png","SPECIES_FURRET":"furret.png","SPECIES_HOOTHOOT":"hoothoot.png","SPECIES_NOCTOWL":"noctowl.png","SPECIES_LEDYBA":"ledyba.png","SPECIES_LEDIAN":"ledian.png","SPECIES_SPINARAK":"spinarak.png","SPECIES_ARIADOS":"ariados.png","SPECIES_CROBAT":"crobat.png","SPECIES_CHINCHOU":"chinchou.png","SPECIES_LANTURN":"lanturn.png","SPECIES_PICHU":"pichu.png","SPECIES_CLEFFA":"cleffa.png","SPECIES_IGGLYBUFF":"igglybuff.png","SPECIES_TOGEPI":"togepi.png","SPECIES_TOGETIC":"togetic.png","SPECIES_NATU":"natu.png","SPECIES_XATU":"xatu.png","SPECIES_MAREEP":"mareep.png","SPECIES_FLAAFFY":"flaaffy.png","SPECIES_AMPHAROS":"ampharos.png","SPECIES_BELLOSSOM":"bellossom.png","SPECIES_MARILL":"marill.png","SPECIES_AZUMARILL":"azumarill.png","SPECIES_SUDOWOODO":"sudowoodo.png","SPECIES_POLITOED":"politoed.png","SPECIES_HOPPIP":"hoppip.png","SPECIES_SKIPLOOM":"skiploom.png","SPECIES_JUMPLUFF":"jumpluff.png","SPECIES_AIPOM":"aipom.png","SPECIES_SUNKERN":"sunkern.png","SPECIES_SUNFLORA":"sunflora.png","SPECIES_YANMA":"yanma.png","SPECIES_WOOPER":"wooper.png","SPECIES_QUAGSIRE":"quagsire.png","SPECIES_ESPEON":"espeon.png","SPECIES_UMBREON":"umbreon.png","SPECIES_MURKROW":"murkrow.png","SPECIES_SLOWKING":"slowking.png","SPECIES_MISDREAVUS":"misdreavus.png","SPECIES_UNOWN":"unown_a.png","SPECIES_WOBBUFFET":"wobbuffet.png","SPECIES_GIRAFARIG":"girafarig.png","SPECIES_PINECO":"pineco.png","SPECIES_FORRETRESS":"forretress.png","SPECIES_DUNSPARCE":"dunsparce.png","SPECIES_GLIGAR":"gligar.png","SPECIES_STEELIX":"steelix.png","SPECIES_SNUBBULL":"snubbull.png","SPECIES_GRANBULL":"granbull.png","SPECIES_QWILFISH":"qwilfish.png","SPECIES_SCIZOR":"scizor.png","SPECIES_SHUCKLE":"shuckle.png","SPECIES_HERACROSS":"heracross.png","SPECIES_SNEASEL":"sneasel.png","SPECIES_TEDDIURSA":"teddiursa.png","SPECIES_URSARING":"ursaring.png","SPECIES_SLUGMA":"slugma.png","SPECIES_MAGCARGO":"magcargo.png","SPECIES_SWINUB":"swinub.png","SPECIES_PILOSWINE":"piloswine.png","SPECIES_CORSOLA":"corsola.png","SPECIES_REMORAID":"remoraid.png","SPECIES_OCTILLERY":"octillery.png","SPECIES_DELIBIRD":"delibird.png","SPECIES_MANTINE":"mantine.png","SPECIES_SKARMORY":"skarmory.png","SPECIES_HOUNDOUR":"houndour.png","SPECIES_HOUNDOOM":"houndoom.png","SPECIES_KINGDRA":"kingdra.png","SPECIES_PHANPY":"phanpy.png","SPECIES_DONPHAN":"donphan.png","SPECIES_PORYGON2":"porygon2.png","SPECIES_STANTLER":"stantler.png","SPECIES_SMEARGLE":"smeargle.png","SPECIES_TYROGUE":"tyrogue.png","SPECIES_HITMONTOP":"hitmontop.png","SPECIES_SMOOCHUM":"smoochum.png","SPECIES_ELEKID":"elekid.png","SPECIES_MAGBY":"magby.png","SPECIES_MILTANK":"miltank.png","SPECIES_BLISSEY":"blissey.png","SPECIES_RAIKOU":"raikou.png","SPECIES_ENTEI":"entei.png","SPECIES_SUICUNE":"suicune.png","SPECIES_LARVITAR":"larvitar.png","SPECIES_PUPITAR":"pupitar.png","SPECIES_TYRANITAR":"tyranitar.png","SPECIES_LUGIA":"lugia.png","SPECIES_HO_OH":"ho_oh.png","SPECIES_CELEBI":"celebi.png"},"areaAliases":{},"areaMapsByVersion":{}}
