=== trowgundam/pokemon_field_guide/schemas/pokedex.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://pokemon-field-guide.local/schemas/pokedex.schema.json",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "number": {
        "type": "integer",
        "minimum": 1,
        "maximum": 2147483647
      },
      "regionalNumber": {
        "type": [
          "integer",
          "null"
        ],
        "minimum": 1,
        "maximum": 2147483647
      },
      "name": {
        "type": "string"
      },
      "speciesId": {
        "type": "string"
      },
      "availability": {
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      }
    },
    "required": [
      "number",
      "name",
      "speciesId",
      "availability"
    ],
    "additionalProperties": false
  }
}

=== trowgundam/pokemon_field_guide/PokemonFieldGuide/wwwroot/games/rb/data/pokedex.json
[{"number":1,"regionalNumber":1,"name":"Bulbasaur","speciesId":"SPECIES_BULBASAUR","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":2,"regionalNumber":2,"name":"Ivysaur","speciesId":"SPECIES_IVYSAUR","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":3,"regionalNumber":3,"name":"Venusaur","speciesId":"SPECIES_VENUSAUR","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":4,"regionalNumber":4,"name":"Charmander","speciesId":"SPECIES_CHARMANDER","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":5,"regionalNumber":5,"name":"Charmeleon","speciesId":"SPECIES_CHARMELEON","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":6,"regionalNumber":6,"name":"Charizard","speciesId":"SPECIES_CHARIZARD","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":7,"regionalNumber":7,"name":"Squirtle","speciesId":"SPECIES_SQUIRTLE","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":8,"regionalNumber":8,"name":"Wartortle","speciesId":"SPECIES_WARTORTLE","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":9,"regionalNumber":9,"name":"Blastoise","speciesId":"SPECIES_BLASTOISE","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":10,"regionalNumber":10,"name":"Caterpie","speciesId":"SPECIES_CATERPIE","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":11,"regionalNumber":11,"name":"Metapod","speciesId":"SPECIES_METAPOD","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":12,"regionalNumber":12,"name":"Butterfree","speciesId":"SPECIES_BUTTERFREE","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":13,"regionalNumber":13,"name":"Weedle","speciesId":"SPECIES_WEEDLE","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":14,"regionalNumber":14,"name":"Kakuna","speciesId":"SPECIES_KAKUNA","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":15,"regionalNumber":15,"name":"Beedrill","speciesId":"SPECIES_BEEDRILL","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":16,"regionalNumber":16,"name":"Pidgey","speciesId":"SPECIES_PIDGEY","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":17,"regionalNumber":17,"name":"Pidgeotto","speciesId":"SPECIES_PIDGEOTTO","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":18,"regionalNumber":18,"name":"Pidgeot","speciesId":"SPECIES_PIDGEOT","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":19,"regionalNumber":19,"name":"Rattata","speciesId":"SPECIES_RATTATA","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":20,"regionalNumber":20,"name":"Raticate","speciesId":"SPECIES_RATICATE","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":21,"regionalNumber":21,"name":"Spearow","speciesId":"SPECIES_SPEAROW","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":22,"regionalNumber":22,"name":"Fearow","speciesId":"SPECIES_FEAROW","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":23,"regionalNumber":23,"name":"Ekans","speciesId":"SPECIES_EKANS","availability":{"Red":"Obtainable","Blue":"Trade / transfer required"}},{"number":24,"regionalNumber":24,"name":"Arbok","speciesId":"SPECIES_ARBOK","availability":{"Red":"Obtainable","Blue":"Trade / transfer required"}},{"number":25,"regionalNumber":25,"name":"Pikachu","speciesId":"SPECIES_PIKACHU","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":26,"regionalNumber":26,"name":"Raichu","speciesId":"SPECIES_RAICHU","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":27,"regionalNumber":27,"name":"Sandshrew","speciesId":"SPECIES_SANDSHREW","availability":{"Red":"Trade / transfer required","Blue":"Obtainable"}},{"number":28,"regionalNumber":28,"name":"Sandslash","speciesId":"SPECIES_SANDSLASH","availability":{"Red":"Trade / transfer required","Blue":"Obtainable"}},{"number":29,"regionalNumber":29,"name":"Nidoran♀","speciesId":"SPECIES_NIDORAN_F","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":30,"regionalNumber":30,"name":"Nidorina","speciesId":"SPECIES_NIDORINA","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":31,"regionalNumber":31,"name":"Nidoqueen","speciesId":"SPECIES_NIDOQUEEN","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":32,"regionalNumber":32,"name":"Nidoran♂","speciesId":"SPECIES_NIDORAN_M","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":33,"regionalNumber":33,"name":"Nidorino","speciesId":"SPECIES_NIDORINO","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":34,"regionalNumber":34,"name":"Nidoking","speciesId":"SPECIES_NIDOKING","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":35,"regionalNumber":35,"name":"Clefairy","speciesId":"SPECIES_CLEFAIRY","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":36,"regionalNumber":36,"name":"Clefable","speciesId":"SPECIES_CLEFABLE","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":37,"regionalNumber":37,"name":"Vulpix","speciesId":"SPECIES_VULPIX","availability":{"Red":"Trade / transfer required","Blue":"Obtainable"}},{"number":38,"regionalNumber":38,"name":"Ninetales","speciesId":"SPECIES_NINETALES","availability":{"Red":"Trade / transfer required","Blue":"Obtainable"}},{"number":39,"regionalNumber":39,"name":"Jigglypuff","speciesId":"SPECIES_JIGGLYPUFF","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":40,"regionalNumber":40,"name":"Wigglytuff","speciesId":"SPECIES_WIGGLYTUFF","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":41,"regionalNumber":41,"name":"Zubat","speciesId":"SPECIES_ZUBAT","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":42,"regionalNumber":42,"name":"Golbat","speciesId":"SPECIES_GOLBAT","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":43,"regionalNumber":43,"name":"Oddish","speciesId":"SPECIES_ODDISH","availability":{"Red":"Obtainable","Blue":"Trade / transfer required"}},{"number":44,"regionalNumber":44,"name":"Gloom","speciesId":"SPECIES_GLOOM","availability":{"Red":"Obtainable","Blue":"Trade / transfer required"}},{"number":45,"regionalNumber":45,"name":"Vileplume","speciesId":"SPECIES_VILEPLUME","availability":{"Red":"Obtainable","Blue":"Trade / transfer required"}},{"number":46,"regionalNumber":46,"name":"Paras","speciesId":"SPECIES_PARAS","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":47,"regionalNumber":47,"name":"Parasect","speciesId":"SPECIES_PARASECT","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":48,"regionalNumber":48,"name":"Venonat","speciesId":"SPECIES_VENONAT","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":49,"regionalNumber":49,"name":"Venomoth","speciesId":"SPECIES_VENOMOTH","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":50,"regionalNumber":50,"name":"Diglett","speciesId":"SPECIES_DIGLETT","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":51,"regionalNumber":51,"name":"Dugtrio","speciesId":"SPECIES_DUGTRIO","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":52,"regionalNumber":52,"name":"Meowth","speciesId":"SPECIES_MEOWTH","availability":{"Red":"Trade / transfer required","Blue":"Obtainable"}},{"number":53,"regionalNumber":53,"name":"Persian","speciesId":"SPECIES_PERSIAN","availability":{"Red":"Trade / transfer required","Blue":"Obtainable"}},{"number":54,"regionalNumber":54,"name":"Psyduck","speciesId":"SPECIES_PSYDUCK","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":55,"regionalNumber":55,"name":"Golduck","speciesId":"SPECIES_GOLDUCK","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":56,"regionalNumber":56,"name":"Mankey","speciesId":"SPECIES_MANKEY","availability":{"Red":"Obtainable","Blue":"Trade / transfer required"}},{"number":57,"regionalNumber":57,"name":"Primeape","speciesId":"SPECIES_PRIMEAPE","availability":{"Red":"Obtainable","Blue":"Trade / transfer required"}},{"number":58,"regionalNumber":58,"name":"Growlithe","speciesId":"SPECIES_GROWLITHE","availability":{"Red":"Obtainable","Blue":"Trade / transfer required"}},{"number":59,"regionalNumber":59,"name":"Arcanine","speciesId":"SPECIES_ARCANINE","availability":{"Red":"Obtainable","Blue":"Trade / transfer required"}},{"number":60,"regionalNumber":60,"name":"Poliwag","speciesId":"SPECIES_POLIWAG","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":61,"regionalNumber":61,"name":"Poliwhirl","speciesId":"SPECIES_POLIWHIRL","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":62,"regionalNumber":62,"name":"Poliwrath","speciesId":"SPECIES_POLIWRATH","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":63,"regionalNumber":63,"name":"Abra","speciesId":"SPECIES_ABRA","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":64,"regionalNumber":64,"name":"Kadabra","speciesId":"SPECIES_KADABRA","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":65,"regionalNumber":65,"name":"Alakazam","speciesId":"SPECIES_ALAKAZAM","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":66,"regionalNumber":66,"name":"Machop","speciesId":"SPECIES_MACHOP","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":67,"regionalNumber":67,"name":"Machoke","speciesId":"SPECIES_MACHOKE","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":68,"regionalNumber":68,"name":"Machamp","speciesId":"SPECIES_MACHAMP","availability":{"Red":"Obtainable","Blue":"Obtainable"}},{"number":69,"regionalNumber":69,"name":"Bellsprout","speciesId":"SPECIES_BELLSPROUT","availability":{"Red":"Trade / transfer required","Blue":"Obtainable"}},{"number":70,"regionalNumber":70,"name":"Weepinbell","speciesId":"SPECIES_WEEPINBELL","availability":{"Red":"Trade / transfer required","Blue":"Obtainable"}},{"number":71,"regionalNumber":71,"name":"Victreebel","speciesId":"SPECIES_VICTREEBEL","ava
