=== trowgundam/pokemon_field_guide/schemas/worlds.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://pokemon-field-guide.local/schemas/worlds.schema.json",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": [
          "string",
          "null"
        ],
        "minLength": 1
      },
      "image": {
        "type": "string"
      },
      "width": {
        "type": "integer",
        "minimum": 1,
        "maximum": 2147483647
      },
      "height": {
        "type": "integer",
        "minimum": 1,
        "maximum": 2147483647
      },
      "maps": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "width": {
              "type": "integer",
              "minimum": 1,
              "maximum": 2147483647
            },
            "height": {
              "type": "integer",
              "minimum": 1,
              "maximum": 2147483647
            },
            "markerOffsetX": {
              "type": "integer"
            },
            "markerOffsetY": {
              "type": "integer"
            }
          },
          "required": [
            "id",
            "x",
            "y",
            "width",
            "height"
          ],
          "additionalProperties": false
        }
      }
    },
    "required": [
      "id",
      "image",
      "width",
      "height",
      "maps"
    ],
    "additionalProperties": false
  }
}

=== trowgundam/pokemon_field_guide/PokemonFieldGuide/wwwroot/games/crystal/data/worlds.json
[{"id":"crystal-johto-kanto","image":"games/crystal/maps/WORLD_JOHTO_KANTO.png","width":12000,"height":4752,"maps":[{"id":"MAP_NEW_BARK_TOWN","x":5600,"y":3888,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_29","x":4640,"y":3888,"width":960,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_27","x":5920,"y":3888,"width":1280,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_46","x":4960,"y":3312,"width":320,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_CHERRYGROVE_CITY","x":4000,"y":3888,"width":640,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_26","x":7200,"y":2448,"width":320,"height":1728,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_45","x":5280,"y":2160,"width":320,"height":1440,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_30","x":4160,"y":3024,"width":320,"height":864,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_BLACKTHORN_CITY","x":5280,"y":1584,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_31","x":3840,"y":2736,"width":640,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_44","x":4320,"y":1872,"width":960,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_VIOLET_CITY","x":3200,"y":2448,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_MAHOGANY_TOWN","x":4000,"y":1872,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_32","x":3200,"y":3024,"width":320,"height":1440,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_36","x":2240,"y":2448,"width":960,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_43","x":4000,"y":1008,"width":320,"height":864,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_42","x":3040,"y":1872,"width":960,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_33","x":3200,"y":4464,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_37","x":2560,"y":2160,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_35","x":2240,"y":2736,"width":320,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_LAKE_OF_RAGE","x":3840,"y":432,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ECRUTEAK_CITY","x":2400,"y":1584,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_AZALEA_TOWN","x":2560,"y":4464,"width":640,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_GOLDENROD_CITY","x":2080,"y":3312,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_38","x":1760,"y":1744,"width":640,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_34","x":2240,"y":3888,"width":320,"height":864,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_39","x":1440,"y":1744,"width":320,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_OLIVINE_CITY","x":1280,"y":2320,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_40","x":960,"y":2608,"width":320,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_41","x":480,"y":3184,"width":800,"height":864,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_CIANWOOD_CITY","x":0,"y":3184,"width":480,"height":864,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_PALLET_TOWN","x":8480,"y":3168,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_1","x":8480,"y":2592,"width":320,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_21","x":8480,"y":3456,"width":320,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_VIRIDIAN_CITY","x":8160,"y":2016,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_CINNABAR_ISLAND","x":8480,"y":4032,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_2","x":8320,"y":1152,"width":320,"height":864,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_22","x":7520,"y":2144,"width":640,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_20","x":8800,"y":4032,"width":960,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_PEWTER_CITY","x":8160,"y":576,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_19","x":9760,"y":3744,"width":320,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_3","x":8800,"y":736,"width":960,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_FUCHSIA_CITY","x":9760,"y":3168,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_4","x":9760,"y":736,"width":640,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_18","x":9440,"y":3392,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_15","x":10400,"y":3456,"width":640,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_CERULEAN_CITY","x":10400,"y":576,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_17","x":9120,"y":2176,"width":320,"height":1440,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_14","x":11040,"y":3168,"width":320,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_24","x":10592,"y":288,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_5","x":10560,"y":1152,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_9","x":11040,"y":864,"width":960,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_16","x":9120,"y":1888,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_13","x":11040,"y":2880,"width":960,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_25","x":10592,"y":0,"width":960,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_SAFFRON_CITY","x":10400,"y":1440,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_10_NORTH","x":11680,"y":1152,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_CELADON_CITY","x":9440,"y":1600,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_12","x":11680,"y":2016,"width":320,"height":864,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_6","x":10560,"y":2016,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_7","x":10080,"y":1728,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_8","x":11040,"y":1728,"width":640,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_10_SOUTH","x":11680,"y":1440,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_LAVENDER_TOWN","x":11680,"y":1728,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_11","x":11040,"y":2304,"width":640,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_VERMILION_CITY","x":10400,"y":2304,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_28","x":6560,"y":2144,"width":640,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_SILVER_CAVE_OUTSIDE","x":5920,"y":1856,"width":640,"height":576,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_ROUTE_23","x":7200,"y":1840,"width":320,"height":288,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_BATTLE_TOWER_OUTSIDE","x":960,"y":2288,"width":320,"height":320,"markerOffsetX":0,"markerOffsetY":0},{"id":"MAP_VICTORY_ROAD_OVERWORLD","x":7200,"y":2128,"width":320,"height":320,"markerOffsetX":0,"markerOffsetY":0}]}]

=== trowgundam/pokemon_field_guide/PokemonFieldGuide/wwwroot/games/yellow/data/worlds.json
[{"id":"yellow-kanto","image":"games/yellow/maps/WORLD_KANTO.png","width":5440,"height":5760,"maps":[{"id":"MAP_PALLET_TOWN","x":800,"y":3744,"width":320,"height":288},{"id":"MAP_ROUTE_1","x":800,"y":3168,"width":320,"height":576},{"id":"MAP_ROUTE_21","x":800,"y":4032,"width":320,"height":1440},{"id":"MAP_VIRIDIAN_CITY","x":640,"y":2592,"width":640,"height":576},{"id":"MAP_CINNABAR_ISLAND","x":800,"y":5472,"width":320,"height":288},{"id":"MAP_ROUTE_2","x":800,"y":1440,"width":320,"height":1152},{"id":"MAP_ROUTE_22","x":0,"y":2720,"width":640,"height":288},{"id":"MAP_ROUTE_20","x":1120,"y":5472,"width":1600,"height":288},{"id":"MAP_PEWTER_CITY","x":640,"y":864,"width":640,"height":576},{"id":"MAP_ROUTE_23","x":0,"y":416,"width":320,"height":2304},{"id":"MAP_ROUTE_19","x":2720,"y":4896,"width":320,"height":864},{"id":"MAP_ROUTE_3","x":1280,"y":992,"width":1120,"height":288},{"id":"MAP_INDIGO_PLATEAU","x":0,"y":128,"width":320,"height":288},{"id":"MAP_FUCHSIA_CITY","x":2560,"y":4320,"width":640,"height":576},{"id":"MAP_ROUTE_4","x":2080,"y":704,"width":1440,"height":288},{"id":"MAP_ROUTE_18","x":1760,"y":4448,"width":800,"height":288},{"id":"MAP_ROUTE_15","x":3200,"y":4448,"width":960,"height":288},{"id":"MAP_CERULEAN_CITY","x":3520,"y":576,"width":640,"height":576},{"id":"MAP_ROUTE_17","x":1760,"y":2144,"width":320,"height":2304},{"id":"MAP_ROUTE_14","x":4160,"y":3872,"width":320,"height":864},{"id":"MAP_ROUTE_24","x":3680,"y":0,"width":320,"height":576},{"id":"MAP_ROUTE_5","x":3680,"y":1152,"width":320,"height":576},{"id":"MAP_ROUTE_9","x":4160,"y":704,"width":960,"height":288},{"id":"MAP_ROUTE_16","x":1760,"y":1856,"width":640,"height":288},{"id":"MAP_ROUTE_13","x":4480,"y":3872,"width":960,"height":288},{"id":"MAP_ROUTE_25","x":4000,"y":0,"width":960,"height":288},{"id":"MAP_SAFFRON_CITY","x":3520,"y":1728,"width":640,"height":576},{"id":"MAP_ROUTE_10","x":5120,"y":704,"width":320,"height":1152},{"id":"MAP_CELADON_CITY","x":2400,"y":1728,"width":800,"height":576},{"id":"MAP_ROUTE_12","x":5120,"y":2144,"width":320,"height":1728},{"id":"MAP_ROUTE_6","x":3680,"y":2304,"width":320,"height":576},{"id":"MAP_ROUTE_7","x":3200,"y":1856,"width":320,"height":288},{"id":"MAP_ROUTE_8","x":4160,"y":1856,"width":960,"height":288},{"id":"MAP_LAVENDER_TOWN","x":5120,"y":1856,"width":320,"height":288},{"id":"MAP_ROUTE_11","x":4160,"y":3008,"width":960,"height":288},{"id":"MAP_VERMILION_CITY","x":3520,"y":2880,"width":640,"height":576}]}]

=== trowgundam/pokemon_field_guide/PokemonFieldGuide/wwwroot/games/rs/data/worlds.json
[{"id":"rs-hoenn","name":"Hoenn","image":"games/rs/maps/WORLD_RS_HOENN.png","width":12800,"height":6080,"maps":[{"id":"MAP_LITTLEROOT_TOWN","x":1920,"y":4480,"width":320,"height":320},{"id":"MAP_ROUTE101","x":1920,"y":4160,"width":320,"height":320},{"id":"MAP_OLDALE_TOWN","x":1920,"y":3840,"width":320,"height":320},{"id":"MAP_ROUTE103","x":1920,"y":3520,"width":1280,"height":320},{"id":"MAP_ROUTE102","x":1120,"y":3840,"width":800,"height":320},{"id":"MAP_ROUTE110","x":3200,"y":2560,"width":640,"height":1600},{"id":"MAP_PETALBURG_CITY","x":640,"y":3680,"width":480,"height":480},{"id":"MAP_MAUVILLE_CITY","x":3200,"y":2240,"width":640,"height":320},{"id":"MAP_SLATEPORT_CITY","x":3200,"y":4160,"width":640,"height":960},{"id":"MAP_ROUTE104","x":0,"y":2880,"width":640,"height":1280},{"id":"MAP_ROUTE111","x":3200,"y":0,"width":640,"height":2240},{"id":"MAP_ROUTE117","x":2240,"y":2240,"width":960,"height":320},{"id":"MAP_ROUTE118","x":3840,"y":2240,"width":1280,"height":320},{"id":"MAP_ROUTE109","x":3200,"y":5120,"width":640,"height":960},{"id":"MAP_ROUTE134","x":3840,"y":4160,"width":1280,"height":640},{"id":"MAP_RUSTBORO_CITY","x":0,"y":1920,"width":640,"height":960},{"id":"MAP_ROUTE105","x":0,"y":4160,"width":640,"height":1280},{"id":"MAP_ROUTE113","x":1600,"y":0,"width":1600,"height":320},{"id":"MAP_ROUTE112","x":2560,"y":320,"width":640,"height":960},{"id":"MAP_VERDANTURF_TOWN","x":1920,"y":2240,"width":320,"height":320},{"id":"MAP_ROUTE119","x":4480,"y":0,"width":640,"height":2240},{"id":"MAP_ROUTE123","x":5120,"y":2240,"width":2240,"height":320},{"id":"MAP_ROUTE108","x":2240,"y":5760,"width":960,"height":320},{"id":"MAP_ROUTE133","x":5120,"y":4160,"width":1280,"height":640},{"id":"MAP_ROUTE115","x":0,"y":640,"width":640,"height":1280},{"id":"MAP_ROUTE116","x":640,"y":1920,"width":1600,"height":320},{"id":"MAP_ROUTE106","x":0,"y":5440,"width":1280,"height":320},{"id":"MAP_FALLARBOR_TOWN","x":1280,"y":0,"width":320,"height":320},{"id":"MAP_LAVARIDGE_TOWN","x":2240,"y":960,"width":320,"height":320},{"id":"MAP_FORTREE_CITY","x":5120,"y":0,"width":640,"height":320},{"id":"MAP_ROUTE122","x":6720,"y":1600,"width":640,"height":640},{"id":"MAP_ROUTE107","x":1280,"y":5760,"width":960,"height":320},{"id":"MAP_ROUTE132","x":6400,"y":4160,"width":1280,"height":640},{"id":"MAP_ROUTE114","x":640,"y":0,"width":640,"height":1280},{"id":"MAP_DEWFORD_TOWN","x":960,"y":5760,"width":320,"height":320},{"id":"MAP_ROUTE120","x":5760,"y":0,"width":640,"height":1600},{"id":"MAP_ROUTE121","x":6400,"y":1280,"width":1280,"height":320},{"id":"MAP_PACIFIDLOG_TOWN","x":7680,"y":4160,"width":320,"height":640},{"id":"MAP_LILYCOVE_CITY","x":7680,"y":1120,"width":1280,"height":640},{"id":"MAP_ROUTE131","x":8000,"y":4160,"width":960,"height":640},{"id":"MAP_ROUTE124","x":8960,"y":960,"width":1280,"height":1280},{"id":"MAP_ROUTE130","x":8960,"y":4160,"width":1280,"height":640},{"id":"MAP_ROUTE126","x":8960,"y":2240,"width":1280,"height":1280},{"id":"MAP_ROUTE125","x":10240,"y":960,"width":1280,"height":640},{"id":"MAP_MOSSDEEP_CITY","x":10240,"y":1600,"width":1280,"height":640},{"id":"MAP_ROUTE129","x":10240,"y":4160,"width":1280,"height":640},{"id":"MAP_ROUTE127","x":10240,"y":2240,"width":1280,"height":1280},{"id":"MAP_ROUTE128","x":10240,"y":3520,"width":1920,"height":640},{"id":"MAP_EVER_GRANDE_CITY","x":12160,"y":2880,"width":640,"height":1280}]},{"id":"rs-underwater","name":"Underwater","image":"games/rs/maps/WORLD_RS_UNDERWATER.png","width":3200,"height":3200,"maps":[{"id":"MAP_UNDERWATER1","x":0,"y":0,"width":1280,"height":1280},{"id":"MAP_UNDERWATER2","x":0,"y":1280,"width":1280,"height":1280},{"id":"MAP_UNDERWATER3","x":1280,"y":1280,"width":1280,"height":1280},{"id":"MAP_UNDERWATER4","x":1280,"y":2560,"width":1920,"height":640}]},{"id":"rs-battle-tower","name":"Battle Tower","image":"games/rs/maps/WORLD_RS_BATTLE_TOWER.png","width":464,"height":480,"maps":[{"id":"MAP_BATTLE_TOWER_OUTSIDE","x":0,"y":0,"width":464,"height":480}]}]

=== trowgundam/pokemon_field_guide/PokemonFieldGuide/wwwroot/games/emerald/data/worlds.json
[{"id":"emerald-hoenn","name":"Hoenn","image":"games/emerald/maps/WORLD_EMERALD_HOENN.png","width":12800,"height":6128,"maps":[{"id":"MAP_LITTLEROOT_TOWN","x":1920,"y":4512,"width":320,"height":320},{"id":"MAP_ROUTE101","x":1920,"y":4192,"width":320,"height":320},{"id":"MAP_OLDALE_TOWN","x":1920,"y":3872,"width":320,"height":320},{"id":"MAP_ROUTE103","x":1920,"y":3520,"width":1280,"height":352},{"id":"MAP_ROUTE102","x":1120,"y":3872,"width":800,"height":320},{"id":"MAP_ROUTE110","x":3200,"y":2560,"width":640,"height":1600},{"id":"MAP_PETALBURG_CITY","x":640,"y":3712,"width":480,"height":480},{"id":"MAP_MAUVILLE_CITY","x":3200,"y":2240,"width":640,"height":320},{"id":"MAP_SLATEPORT_CITY","x":3200,"y":4160,"width":640,"height":960},{"id":"MAP_ROUTE104","x":0,"y":2912,"width":640,"height":1280},{"id":"MAP_ROUTE111","x":3200,"y":0,"width":640,"height":2240},{"id":"MAP_ROUTE117","x":2240,"y":2240,"width":960,"height":320},{"id":"MAP_ROUTE118","x":3840,"y":2240,"width":1280,"height":320},{"id":"MAP_ROUTE109","x":3200,"y":5120,"width":640,"height":1008},{"id":"MAP_ROUTE134","x":3840,"y":4160,"width":1280,"height":640},{"id":"MAP_RUSTBORO_CITY","x":0,"y":1952,"width":640,"height":960},{"id":"MAP_ROUTE105","x":0,"y":4192,"width":640,"height":1280},{"id":"MAP_ROUTE113","x":1600,"y":0,"width":1600,"height":320},{"id":"MAP_ROUTE112","x":2560,"y":320,"width":640,"height":960},{"id":"MAP_VERDANTURF_TOWN","x":1920,"y":2240,"width":320,"height":320},{"id":"MAP_ROUTE119","x":4480,"y":0,"width":640,"height":2240},{"id":"MAP_ROUTE123","x":5120,"y":2240,"width":2240,"height":320},{"id":"MAP_ROUTE108","x":2240,"y":5760,"width":960,"height":320},{"id":"MAP_ROUTE133","x":5120,"y":4160,"width":1280,"height":640},{"id":"MAP_ROUTE115","x":0,"y":672,"width":640,"height":1280},{"id":"MAP_ROUTE116","x":640,"y":1952,"width":1600,"height":320},{"id":"MAP_ROUTE106","x":0,"y":5472,"width":1280,"height":320},{"id":"MAP_FALLARBOR_TOWN","x":1280,"y":0,"width":320,"height":320},{"id":"MAP_LAVARIDGE_TOWN","x":2240,"y":960,"width":320,"height":320},{"id":"MAP_FORTREE_CITY","x":5120,"y":0,"width":640,"height":320},{"id":"MAP_ROUTE122","x":6720,"y":1600,"width":640,"height":640},{"id":"MAP_ROUTE107","x":1280,"y":5760,"width":960,"height":320},{"id":"MAP_ROUTE132","x":6400,"y":4160,"width":1280,"height":640},{"id":"MAP_ROUTE114","x":640,"y":32,"width":640,"height":1280},{"id":"MAP_DEWFORD_TOWN","x":960,"y":5792,"width":320,"height":320},{"id":"MAP_ROUTE120","x":5760,"y":0,"width":640,"height":1600},{"id":"MAP_ROUTE121","x":6400,"y":1280,"width":1280,"height":320},{"id":"MAP_PACIFIDLOG_TOWN","x":7680,"y":4160,"width":320,"height":640},{"id":"MAP_LILYCOVE_CITY","x":7680,"y":1120,"width":1280,"height":640},{"id":"MAP_ROUTE131","x":8000,"y":4160,"width":960,"height":640},{"id":"MAP_ROUTE124","x":8960,"y":960,"width":1280,"height":1280},{"id":"MAP_ROUTE130","x":8960,"y":4160,"width":1280,"height":640},{"id":"MAP_ROUTE126","x":8960,"y":2240,"width":1280,"height":1280},{"id":"MAP_ROUTE125","x":10240,"y":960,"width":1280,"height":640},{"id":"MAP_MOSSDEEP_CITY","x":10240,"y":1600,"width":1280,"height":640},{"id":"MAP_ROUTE129","x":10240,"y":4160,"width":1280,"height":640},{"id":"MAP_ROUTE127","x":10240,"y":2240,"width":1280,"height":1280},{"id":"MAP_ROUTE128","x":10240,"y":3520,"width":1920,"height":640},{"id":"MAP_EVER_GRANDE_CITY","x":12160,"y":2880,"width":640,"height":1280}]},{"id":"emerald-underwater","name":"Underwater","image":"games/emerald/maps/WORLD_EMERALD_UNDERWATER.png","width":3200,"height":3200,"maps":[{"id":"MAP_UNDERWATER_ROUTE124","x":0,"y":0,"width":1280,"height":1280},{"id":"MAP_UNDERWATER_ROUTE126","x":0,"y":1280,"width":1280,"height":1280},{"id":"MAP_UNDERWATER_ROUTE127","x":1280,"y":1280,"width":1280,"height":1280},{"id":"MAP_UNDERWATER_ROUTE128","x":1280,"y":2560,"width":1920,"height":640}]},{"id":"emerald-battle-frontier","name":"Battle Frontier","image":"games/emerald/maps/WORLD_EMERALD_BATTLE_FRONTIER.png","width":2048,"height":1152,"maps":[{"id":"MAP_BATTLE_FRONTIER_OUTSIDE_WEST","x":0,"y":0,"width":896,"height":1152},{"id":"MAP_BATTLE_FRONTIER_OUTSIDE_EAST","x":896,"y":0,"width":1152,"height":1152}]}]

=== trowgundam/pokemon_field_guide/PokemonFieldGuide/wwwroot/games/frlg/data/worlds.json
[{"id":"kanto","image":"games/frlg/maps/WORLD_KANTO.png","width":6528,"height":6400,"maps":[{"id":"MAP_PALLET_TOWN","x":960,"y":4160,"width":384,"height":320},{"id":"MAP_ROUTE1","x":960,"y":3520,"width":384,"height":640},{"id":"MAP_ROUTE21_NORTH","x":960,"y":4480,"width":384,"height":800},{"id":"MAP_VIRIDIAN_CITY","x":768,"y":2880,"width":768,"height":640},{"id":"MAP_ROUTE21_SOUTH","x":960,"y":5280,"width":384,"height":800},{"id":"MAP_ROUTE2","x":960,"y":1600,"width":384,"height":1280},{"id":"MAP_ROUTE22","x":0,"y":3040,"width":768,"height":384},{"id":"MAP_CINNABAR_ISLAND","x":960,"y":6080,"width":384,"height":320},{"id":"MAP_PEWTER_CITY","x":768,"y":960,"width":768,"height":640},{"id":"MAP_ROUTE23","x":0,"y":480,"width":384,"height":2560},{"id":"MAP_ROUTE20","x":1344,"y":6080,"width":1920,"height":320},{"id":"MAP_ROUTE3","x":1536,"y":1120,"width":1344,"height":320},{"id":"MAP_INDIGO_PLATEAU_EXTERIOR","x":0,"y":160,"width":384,"height":320},{"id":"MAP_ROUTE19","x":3264,"y":5440,"width":384,"height":960},{"id":"MAP_ROUTE4","x":2496,"y":800,"width":1728,"height":320},{"id":"MAP_FUCHSIA_CITY","x":3072,"y":4800,"width":768,"height":640},{"id":"MAP_CERULEAN_CITY","x":4224,"y":640,"width":768,"height":640},{"id":"MAP_ROUTE18","x":2112,"y":4960,"width":960,"height":320},{"id":"MAP_ROUTE15","x":3840,"y":4960,"width":1152,"height":320},{"id":"MAP_ROUTE24","x":4416,"y":0,"width":384,"height":640},{"id":"MAP_ROUTE5","x":4224,"y":1280,"width":768,"height":640},{"id":"MAP_ROUTE9","x":4992,"y":800,"width":1152,"height":320},{"id":"MAP_ROUTE17","x":2112,"y":2400,"width":384,"height":2560},{"id":"MAP_ROUTE14","x":4992,"y":4320,"width":384,"height":960},{"id":"MAP_ROUTE25","x":4800,"y":0,"width":1152,"height":320},{"id":"MAP_SAFFRON_CITY","x":4224,"y":1920,"width":768,"height":640,"markerOffsetX":10,"markerOffsetY":7},{"id":"MAP_ROUTE10","x":6144,"y":800,"width":384,"height":1280},{"id":"MAP_ROUTE16","x":2112,"y":2080,"width":768,"height":320},{"id":"MAP_ROUTE13","x":5376,"y":4320,"width":1152,"height":320},{"id":"MAP_ROUTE6","x":4416,"y":2560,"width":384,"height":640},{"id":"MAP_ROUTE7","x":3840,"y":2080,"width":384,"height":320},{"id":"MAP_ROUTE8","x":4992,"y":2080,"width":1152,"height":320},{"id":"MAP_LAVENDER_TOWN","x":6144,"y":2080,"width":384,"height":320},{"id":"MAP_CELADON_CITY","x":2880,"y":1920,"width":960,"height":640},{"id":"MAP_ROUTE12","x":6144,"y":2400,"width":384,"height":1920},{"id":"MAP_VERMILION_CITY","x":4224,"y":3200,"width":768,"height":640},{"id":"MAP_ROUTE11","x":4992,"y":3360,"width":1152,"height":320}]},{"id":"sevii","image":"games/frlg/maps/WORLD_SEVII.png","width":16448,"height":4160,"maps":[{"id":"MAP_ONE_ISLAND","x":0,"y":1920,"width":384,"height":320},{"id":"MAP_ONE_ISLAND_TREASURE_BEACH","x":0,"y":2240,"width":384,"height":640},{"id":"MAP_ONE_ISLAND_KINDLE_ROAD","x":384,"y":0,"width":384,"height":2240},{"id":"MAP_TWO_ISLAND","x":960,"y":1920,"width":768,"height":320},{"id":"MAP_TWO_ISLAND_CAPE_BRINK","x":1344,"y":1280,"width":384,"height":640},{"id":"MAP_THREE_ISLAND","x":3456,"y":1920,"width":384,"height":640},{"id":"MAP_THREE_ISLAND_PORT","x":3456,"y":2560,"width":768,"height":320},{"id":"MAP_THREE_ISLAND_BOND_BRIDGE","x":1920,"y":1920,"width":1536,"height":320},{"id":"MAP_FOUR_ISLAND","x":4416,"y":1920,"width":768,"height":640},{"id":"MAP_FIVE_ISLAND","x":6144,"y":1920,"width":384,"height":320},{"id":"MAP_FIVE_ISLAND_WATER_LABYRINTH","x":5376,"y":1600,"width":1152,"height":320},{"id":"MAP_FIVE_ISLAND_MEADOW","x":6528,"y":1920,"width":384,"height":640},{"id":"MAP_FIVE_ISLAND_RESORT_GORGEOUS","x":6144,"y":1280,"width":1152,"height":320},{"id":"MAP_FIVE_ISLAND_MEMORIAL_PILLAR","x":6912,"y":2240,"width":384,"height":960},{"id":"MAP_SEVEN_ISLAND","x":8256,"y":1920,"width":384,"height":320},{"id":"MAP_SEVEN_ISLAND_TRAINER_TOWER","x":7488,"y":1280,"width":1920,"height":640},{"id":"MAP_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE","x":8256,"y":2240,"width":384,"height":640},{"id":"MAP_SEVEN_ISLAND_SEVAULT_CANYON","x":8640,"y":2560,"width":384,"height":1280},{"id":"MAP_SEVEN_ISLAND_TANOBY_RUINS","x":7872,"y":3840,"width":2304,"height":320},{"id":"MAP_SIX_ISLAND","x":11136,"y":1920,"width":384,"height":480},{"id":"MAP_SIX_ISLAND_WATER_PATH","x":11520,"y":1280,"width":384,"height":1600},{"id":"MAP_SIX_ISLAND_GREEN_PATH","x":10368,"y":1280,"width":1152,"height":320},{"id":"MAP_SIX_ISLAND_RUIN_VALLEY","x":10752,"y":2560,"width":768,"height":640},{"id":"MAP_SIX_ISLAND_OUTCAST_ISLAND","x":10368,"y":0,"width":384,"height":1280},{"id":"MAP_THREE_ISLAND_BERRY_FOREST","x":12096,"y":1920,"width":912,"height":752},{"id":"MAP_MT_EMBER_EXTERIOR","x":13200,"y":1920,"width":912,"height":864},{"id":"MAP_SIX_ISLAND_PATTERN_BUSH","x":14304,"y":1920,"width":960,"height":512},{"id":"MAP_BIRTH_ISLAND_EXTERIOR","x":15456,"y":1920,"width":480,"height":480},{"id":"MAP_NAVEL_ROCK_EXTERIOR","x":16128,"y":1920,"width":320,"height":368}]}]
